format = """
$os\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""


[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[aws]
symbol = "  "
disabled = true

[buf]
symbol = " "
disabled = true

[c]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[crystal]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[fennel]
symbol = " "
disabled = true

[fossil_branch]
symbol = " "
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "
disabled = true

[guix_shell]
symbol = " "
disabled = true

[haskell]
symbol = " "
disabled = true

[haxe]
symbol = " "
disabled = true

[hg_branch]
symbol = " "
disabled = true

[hostname]
ssh_symbol = " "
disabled = true

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[kotlin]
symbol = " "
disabled = true

[lua]
symbol = " "
disabled = true

[memory_usage]
symbol = "󰍛 "
disabled = true

[meson]
symbol = "󰔷 "
disabled = true

[nim]
symbol = "󰆥 "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[ocaml]
symbol = " "
disabled = true

[os]
disabled = false
format = " [$symbol](white) "
[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[pijul_channel]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[rlang]
symbol = "󰟔 "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[scala]
symbol = " "
disabled = true

[swift]
symbol = " "
disabled = true

[zig]
symbol = " "
disabled = true
