

[window]
padding = { x = 0, y = 0 }
decorations = "None"
startup_mode = "Maximized"
opacity = 0.7
blur = true

[scrolling]
history = 10000

[font]
normal = { family = "FiraCode Nerd Font" }
size = 18
